name: Train & Deploy Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    name: Train Model (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python src/train.py

      - name: Extract metrics
        id: metric
        run: |
          METRIC=$(cat metrics.json | jq -r '.accuracy')
          echo "metric=$METRIC" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            outputs/model.pkl
            metrics.json

  deploy:
    name: Deploy Model (CD)
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: trained-model

      - name: Read new metric
        id: new
        run: echo "NEW_METRIC=$(cat metrics.json | jq -r '.accuracy')" >> $GITHUB_ENV

      - name: Read best metric
        id: best
        run: echo "BEST_METRIC=${{ vars.BEST_METRIC }}" >> $GITHUB_ENV

      - name: Compare metrics
        id: compare
        run: |
          echo "NEW: $NEW_METRIC | BEST: $BEST_METRIC"
          awk -v new="$NEW_METRIC" -v best="$BEST_METRIC" 'BEGIN { exit !(new > best) }'

      - name: No improvement â€” exit
        if: failure()
        run: echo "${{ github.actor }} ---- Metric did not improve" && exit 0

      - name: Checkout code for docker build
        if: success()
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2-model:latest

      - name: Update BEST_METRIC variable
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.updateRepoVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'BEST_METRIC',
              value: process.env.NEW_METRIC
            })
